import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.3';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { format, period, metrics } = await req.json();

    console.log('Exporting report:', { format, period });

    // Generate export data based on format
    let exportData: any;
    let contentType: string;
    let filename: string;

    if (format === 'excel') {
      // Generate CSV format (simplified Excel alternative)
      const csvRows: string[] = [
        '# AETS Platform Report',
        `# Period: Last ${period} days`,
        `# Generated: ${new Date().toISOString()}`,
        '',
        '## Token Issuance by Merchant',
        'Merchant,Token Count',
        ...metrics.tokenIssuance.map((m: any) => `${m.merchant},${m.tokens}`),
        '',
        '## Average Latency',
        'Date,Avg Latency (ms)',
        ...metrics.latencyData.map((d: any) => `${d.date},${d.avgLatency}`),
        '',
        '## Risk Score Distribution',
        'Risk Range,Count',
        ...metrics.riskDistribution.map((r: any) => `${r.range},${r.count}`),
        '',
        '## Compliance Summary',
        'Status,Count',
        ...metrics.complianceSummary.map((c: any) => `${c.status},${c.count}`),
      ];

      exportData = csvRows.join('\n');
      contentType = 'text/csv';
      filename = `aets-report-${Date.now()}.csv`;
    } else if (format === 'pdf') {
      // Generate markdown format (can be converted to PDF)
      const mdContent = `
# AETS Platform Report

**Period:** Last ${period} days  
**Generated:** ${new Date().toLocaleString()}

---

## Executive Summary

### Token Issuance
${metrics.tokenIssuance.map((m: any) => `- **${m.merchant}:** ${m.tokens} tokens`).join('\n')}

### Performance Metrics
- **Average Latency:** ${metrics.latencyData.length > 0 ? Math.round(metrics.latencyData.reduce((sum: number, d: any) => sum + d.avgLatency, 0) / metrics.latencyData.length) : 0}ms
- **Total Risk Events:** ${metrics.riskDistribution.reduce((sum: number, r: any) => sum + r.count, 0)}

### Risk Distribution
${metrics.riskDistribution.map((r: any) => `- **${r.range}:** ${r.count} events`).join('\n')}

### Compliance Status
${metrics.complianceSummary.map((c: any) => `- **${c.status.toUpperCase()}:** ${c.count}`).join('\n')}

---

## Detailed Analysis

### Authorization Latency Trends
${metrics.latencyData.map((d: any) => `- ${d.date}: ${d.avgLatency}ms`).join('\n')}

### Risk Management
The risk scoring system identified ${metrics.riskDistribution.reduce((sum: number, r: any) => sum + r.count, 0)} total events during this period. 
${metrics.riskDistribution.find((r: any) => r.range.includes('Critical'))?.count || 0} critical events require immediate attention.

### Compliance Overview
Compliance checks show a ${metrics.complianceSummary.length > 0 ? Math.round((metrics.complianceSummary.find((c: any) => c.status === 'pass')?.count || 0) / metrics.complianceSummary.reduce((sum: number, c: any) => sum + c.count, 0) * 100) : 0}% pass rate.
${metrics.complianceSummary.find((c: any) => c.status === 'fail')?.count || 0 > 0 ? 'Failed checks require immediate remediation.' : 'All systems are compliant with PCI DSS standards.'}

---

*Report generated by AETS Platform*
`;

      exportData = mdContent;
      contentType = 'text/markdown';
      filename = `aets-report-${Date.now()}.md`;
    } else {
      throw new Error('Unsupported format');
    }

    // Log export event
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    await supabase.from('audit_logs').insert({
      entity_type: 'report',
      operation_type: 'export',
      request_data: { format, period },
      response_status: 200,
    });

    return new Response(
      JSON.stringify({
        success: true,
        data: exportData,
        filename,
        contentType,
        message: `Report exported as ${format}`,
      }),
      {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  } catch (error) {
    console.error('Error exporting report:', error);
    return new Response(
      JSON.stringify({ error: 'Internal server error' }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  }
});
